### ISSUE TITLE
`circleci-cli build` fails if you are not following the project (even if you have permissions to rebuild)

### ISSUE THREAD

**Issue by jszwedko** [jszwedko/circleci-cli#2]
Panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40f113]

goroutine 1 [running]:
main.main.func9(0xc8200ba0f0)
        /Users/jszwedko/gopath/src/github.com/jszwedko/circleci-cli/main.go:573 +0x6f3
github.com/jszwedko/circleci-cli/vendor/github.com/codegangsta/cli.Command.Run(0x7db910, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8186e0, 0x13, 0x0, ...)
        /Users/jszwedko/gopath/src/github.com/jszwedko/circleci-cli/vendor/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/jszwedko/circleci-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200a4200, 0xc82000a500, 0x2, 0x2, 0x0, 0x0)
        /Users/jszwedko/gopath/src/github.com/jszwedko/circleci-cli/vendor/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
        /Users/jszwedko/gopath/src/github.com/jszwedko/circleci-cli/main.go:697 +0x3545
```

cc/ @stephenchu

**Comment by jszwedko** [comment]
Having trouble reproducing this now, closing, but will re-open if I encounter again.
